# Generated by Django 5.0.2 on 2024-02-25 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cookingstep',
            old_name='images',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='images',
            new_name='image',
        ),
        migrations.AddField(
            model_name='productquantity',
            name='post_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.post'),
            preserve_default=False,
        ),
    ]
