# Generated by Django 5.0.2 on 2024-02-25 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_images_cookingstep_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productquantity',
            name='post_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.post'),
        ),
    ]
