# Generated by Django 5.0.2 on 2024-02-25 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_productquantity_post_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cookingstep',
            name='image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='cookingstep',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='dish_images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='dish_images/'),
        ),
    ]
