# Generated by Django 5.0.2 on 2024-03-03 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_chef_options_alter_chef_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chef',
            name='nick_name',
            field=models.CharField(default=models.CharField(max_length=10, unique=True), max_length=20),
        ),
        migrations.AlterField(
            model_name='chef',
            name='username',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
