# Generated by Django 5.0.2 on 2024-03-03 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_chef_nick_name_alter_chef_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chef',
            name='nick_name',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='chef',
            name='username',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
