# Generated by Django 5.0.2 on 2024-03-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_chef_nick_name_alter_chef_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chef',
            name='username',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
