# Generated by Django 5.0.2 on 2024-03-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_chef_nick_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='product_id',
            field=models.ManyToManyField(to='myapp.product'),
        ),
    ]
